version: '3'

services:

  arpwatch:
    build: .
    image: casperbiering/arpwatch
    network_mode: host
    volumes:
      - ./var-lib-arpwatch/:/var/lib/arpwatch/
    environment:
#     - ARPWATCH_DEBUG=yes
      - ARPWATCH_INTERFACE=eth0
      - ARPWATCH_NOTIFICATION_EMAIL_SERVER_PORT=587
#     - ARPWATCH_NOTIFICATION_EMAIL_SERVER_USER=username
#     - ARPWATCH_NOTIFICATION_EMAIL_SERVER_PASS=password
#     - ARPWATCH_NOTIFICATION_EMAIL_SERVER_ENCRYPTION=ssl
      - ARPWATCH_NOTIFICATION_EMAIL_SERVER_ENCRYPTION=starttls
#     - ARPWATCH_NOTIFICATION_EMAIL_SERVER_ENCRYPTION=none
      - ARPWATCH_NOTIFICATION_EMAIL_SERVER=smtp.example.com
      - ARPWATCH_NOTIFICATION_EMAIL_TO=user@example.net
      - ARPWATCH_NOTIFICATION_EMAIL_FROM=user@example.com
